sudo: required
services:
  - docker

before-install:
  - docker build -t sharmavinyt/travis-docker-react -f Dockerfile.dev .

script:
  - docker run sharmavinyt/travis-docker-react npm run test -- --coverage