FROM node:alpine as builder

WORKDIR /var/www/html/frontend

COPY package*.json .

RUN npm install

COPY ./src/ ./src/
COPY ./public ./public/
RUN npm run build

FROM nginx:alpine

COPY --from=builder /var/www/html/frontend/build /usr/share/nginx/html